networks:
  todoAppNetword:
    driver: bridge

services: 
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - todoAppNetword
    restart: always
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    networks:
      - todoAppNetword
    restart: always