name: npm audit pr

on: 
  pull_request:
    branches:
      - main

jobs:
  front-scan:
    name: npm audit - Front-end
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oke-py/npm-audit-action@v2
        with:
          audit_level: low
          github_token: ${{ secrets.GITHUB_TOKEN }}
          issue_assignees: TiaSous
          issue_labels: vulnerability,test
          working_directory: ./frontend
  back-scan:
    name: npm audit - Back-end
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oke-py/npm-audit-action@v2
        with:
          audit_level: low
          github_token: ${{ secrets.GITHUB_TOKEN }}
          issue_assignees: TiaSous
          issue_labels: vulnerability,test
          working_directory: ./backend