name: Docker Image CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: test
      run: "echo ${{ env.DOCKER_USERNAME }}"
    -
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build image
      run: | 
        docker build ./frontend --file dockerfile --tag todo-app-frontend:$(date +%s)
        docker build ./backend --file dockerfile --tag todo-app-backend:$(date +%s)
    - name: Push image
      run: docker push ${{secrets.DOCKER_USER}}/TODO-APP-VUE
