name: Docker Image CI

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-deploy-front:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    -
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}


    - name: build frontend latest
      run: docker build -t ${{secrets.DOCKER_USER}}/todo-app-vue-front:latest ./frontend
    - name: build frontend tag
      run: docker build -t ${{secrets.DOCKER_USER}}/todo-app-vue-front:${{ github.ref_name }} ./frontend
    - name: Push image frontend latest
      run: docker push ${{secrets.DOCKER_USER}}/todo-app-vue-front:latest
    - name: Push image frontend tag
      run: docker push ${{secrets.DOCKER_USER}}/todo-app-vue-front:${{ github.ref_name }}
    - name: deploy frontend to azure
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'todo-app-thoti'
        slot-name: 'Production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}

  build-deploy-back:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    -
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: build backend latest
      run: docker build -t ${{secrets.DOCKER_USER}}/todo-app-vue-back:latest ./backend
    - name: build backend tag
      run: docker build -t ${{secrets.DOCKER_USER}}/todo-app-vue-back:${{ github.ref_name }} ./backend
    - name: publish image backend latest
      run: docker push ${{secrets.DOCKER_USER}}/todo-app-vue-back:latest
    - name: publish image backend tag
      run: docker push ${{secrets.DOCKER_USER}}/todo-app-vue-back:${{ github.ref_name }}
    - name: deploy backend to azure
      uses: azure/webapps-deploy@v3
      with:
          app-name: 'todo-app-thoti-api'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_API }}
