name: Docker Image CI

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: test
      run: "echo ${{ env.DOCKER_USERNAME }}"
    -
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}


    - name: build frontend latest
      run: docker build -t ${{secrets.DOCKER_USER}}/todo-app-vue-front:latest ./frontend
    - name: build frontend tag
      run: docker build -t ${{secrets.DOCKER_USER}}/todo-app-vue-back:${{ github.ref_name }} ./frontend
    - name: build backend latest
      run: docker build -t ${{secrets.DOCKER_USER}}/todo-app-vue-back:latest ./backend
    - name: build backend tag
      run: docker build -t ${{secrets.DOCKER_USER}}/todo-app-vue-back:${{ github.ref_name }} ./backend
    - name: Push image frontend
      run: docker push ${{secrets.DOCKER_USER}}/todo-app-vue-front
    - name: publish image backend
      run: docker push ${{secrets.DOCKER_USER}}/todo-app-vue-back
