name: Docker Image CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login to docker
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build image
      run: | 
        docker build ./frontend --file dockerfile --tag todo-app-frontend:$(date +%s)
        docker build ./backend --file dockerfile --tag todo-app-backend:$(date +%s)
    - name: Push image
      run: docker push ${{secrets.DOCKER_USER}}/TODO-APP-VUE
