name: Run e2e tests

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 20.x
      - name: Run backend
        run: |
            cd backend/
            npm ci
            npm run start &

      - name: Run cypress tests
        run: |
            cd frontend/
            npm install
            npm run build
            npm run test:e2e