name: GitHub Actions NodeJS Test
run-name: ${{ github.actor }} is testing out GitHub Actions with node JS
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Change current dir to frontend app
        run: cd frontend/
      - name: Install dependencies
        run: npm ci
