# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - todo-app-thoti-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_504e93166ca34e3aa0d077bc4c363580 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_047a4a8bbfa84c74aa0ef1f99d180ef8 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_504e93166ca34e3aa0d077bc4c363580 }}/docker.io/thomasetml/todo-app-vue-back:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'todo-app-thoti-api'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_e655e408095240dda86a94f6b40e79ce }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_504e93166ca34e3aa0d077bc4c363580 }}/docker.io/thomasetml/todo-app-vue-back:${{ github.sha }}'